name = "BertiniReal"
uuid = "8b637cc7-2014-4e39-a9d5-c563ddfbba53"
authors = ["Juan Camilo Gonzalez Cabrera"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
